<a href="https://colab.research.google.com/github/mmarguerittee/ML_projects/blob/main/REAL_ESTATE_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import re
import numpy as np

In [ ]:
import os
os.getcwd()

'/content'

In [ ]:
test=pd.read_excel('test.xlsx')
train=pd.read_excel('train.xlsx')

In [ ]:
def to_rub(çurrency):
  if çurrency=='RUB':
    return 1
  elif çurrency=='USD':
    return 75.73
  else:
    return 94.08

In [ ]:
train['Стоимость']=train['Валюта'].apply(to_rub)*train['Стоимость']

In [ ]:
train=train.drop('Валюта',axis=1)
test=test.drop('Валюта',axis=1)

In [ ]:
import re

In [ ]:
def extract_number(room_desc):
    numbers = re.findall(r'\d+', room_desc)
    if numbers:
        return sum(int(num) for num in numbers)
    else:
        return 1

In [ ]:
train['Количество комнат']=train['Количество комнат'].astype(str)
test['Количество комнат']=test['Количество комнат'].astype(str)

In [ ]:
train['Количество комнат']=train['Количество комнат'].apply(extract_number)
test['Количество комнат']=test['Количество комнат'].apply(extract_number)

In [ ]:
import re

def split1(df, column_name):
    df = df.copy()

    def extract_count(text, type):
        if pd.isna(text):
            return 0
        match = re.search(rf'{type} \((\d+)\)', text)
        return int(match.group(1)) if match else 0

    df['Балконы'] = df[column_name].apply(lambda x: extract_count(x, 'Балкон'))
    df['Лоджии'] = df[column_name].apply(lambda x: extract_count(x, 'Лоджия'))

    return df

In [ ]:
train = split1(train, 'Балкон')
test = split1(test, 'Балкон')

In [ ]:
import re

def split2(df, column_name):
    df = df.copy()

    def extract_count(text, type):
        if pd.isna(text):
            return 0
        match = re.search(rf'{type} \((\d+)\)', text)
        return int(match.group(1)) if match else 0

    df['Санузел совмещенный'] = df[column_name].apply(lambda x: extract_count(x, 'Совмещенный'))
    df['Санузел раздельный'] = df[column_name].apply(lambda x: extract_count(x, 'Раздельный'))

    return df

In [ ]:
train = split2(train, 'Санузел')
test = split2(test, 'Санузел')

In [ ]:
s = train["Метро"].astype(str).str.strip()

train["Метро_станция"] = (
    s.str.replace(r"^\s*м\.\s*", "", regex=True)
     .str.replace(r"\s*\(.*\)\s*$", "", regex=True)
     .replace({"nan": np.nan})
)

m = s.str.extract(r"\((\d+)\s*мин\s*(пешком|на машине)\)", expand=True)
mins = pd.to_numeric(m[0], errors="coerce")
mode = m[1]

train["Метро_мин_пешком"] = np.where(
    mode.eq("на машине"),
    mins * 2,
    mins
).astype("float")

In [ ]:
s = test["Метро"].astype(str).str.strip()

test["Метро_станция"] = (
    s.str.replace(r"^\s*м\.\s*", "", regex=True)
     .str.replace(r"\s*\(.*\)\s*$", "", regex=True)
     .replace({"nan": np.nan})
)

m = s.str.extract(r"\((\d+)\s*мин\s*(пешком|на машине)\)", expand=True)
mins = pd.to_numeric(m[0], errors="coerce")
mode = m[1]

test["Метро_мин_пешком"] = np.where(
    mode.eq("на машине"),
    mins * 2,
    mins
).astype("float")

In [ ]:
import numpy as np
import pandas as pd

col = "Площадь, м2"

s = train[col].astype(str).str.replace(",", ".", regex=False).str.strip()


parts = s.str.split("/", expand=True)

train["Площадь_общая"] = pd.to_numeric(parts[0], errors="coerce")
train["Площадь_жилая"] = pd.to_numeric(parts[1], errors="coerce") if parts.shape[1] > 1 else np.nan
train["Площадь_кухня"] = pd.to_numeric(parts[2], errors="coerce") if parts.shape[1] > 2 else np.nan

living_share = (train["Площадь_жилая"] / train["Площадь_общая"]).mean(skipna=True)
kitchen_share = (train["Площадь_кухня"] / train["Площадь_общая"]).mean(skipna=True)

mask_total = train["Площадь_общая"].notna()

train.loc[mask_total & train["Площадь_жилая"].isna(), "Площадь_жилая"] = (
    train.loc[mask_total & train["Площадь_жилая"].isna(), "Площадь_общая"] * living_share
)

train.loc[mask_total & train["Площадь_кухня"].isna(), "Площадь_кухня"] = (
    train.loc[mask_total & train["Площадь_кухня"].isna(), "Площадь_общая"] * kitchen_share
)

train[["Площадь_общая","Площадь_жилая","Площадь_кухня"]] = train[["Площадь_общая","Площадь_жилая","Площадь_кухня"]].round(1)

In [ ]:
s = test[col].astype(str).str.replace(",", ".", regex=False).str.strip()
test["Площадь_общая"] = pd.to_numeric(parts[0], errors="coerce")
test["Площадь_жилая"] = pd.to_numeric(parts[1], errors="coerce") if parts.shape[1] > 1 else np.nan
test["Площадь_кухня"] = pd.to_numeric(parts[2], errors="coerce") if parts.shape[1] > 2 else np.nan
mask_total = test["Площадь_общая"].notna()

test.loc[mask_total & test["Площадь_жилая"].isna(), "Площадь_жилая"] = (
    test.loc[mask_total & test["Площадь_жилая"].isna(), "Площадь_общая"] * living_share
)

test.loc[mask_total & test["Площадь_кухня"].isna(), "Площадь_кухня"] = (
    test.loc[mask_total & test["Площадь_кухня"].isna(), "Площадь_общая"] * kitchen_share
)

test[["Площадь_общая","Площадь_жилая","Площадь_кухня"]] = test[["Площадь_общая","Площадь_жилая","Площадь_кухня"]].round(1)

In [ ]:
s = train["Дом"].astype(str).str.strip()

floors = s.str.extract(r"^\s*(\d+)\s*/\s*(\d+)", expand=True)
train["Этаж"] = pd.to_numeric(floors[0], errors="coerce")
train["Этажность"] = pd.to_numeric(floors[1], errors="coerce")

mat = s.str.extract(r",\s*([^,]+)\s*$", expand=True)[0]
train["Материал"] = mat.where(mat.notna() & (mat != ""), np.nan)

train["Материал"] = train["Материал"].astype("string").str.strip()

In [ ]:
s = test["Дом"].astype(str).str.strip()

floors = s.str.extract(r"^\s*(\d+)\s*/\s*(\d+)", expand=True)
test["Этаж"] = pd.to_numeric(floors[0], errors="coerce")
test["Этажность"] = pd.to_numeric(floors[1], errors="coerce")

mat = s.str.extract(r",\s*([^,]+)\s*$", expand=True)[0]
test["Материал"] = mat.where(mat.notna() & (mat != ""), np.nan)

test["Материал"] = test["Материал"].astype("string").str.strip()

In [ ]:
train['Ремонт']=train['Ремонт'].fillna('Без ремонта')
test['Ремонт']=test['Ремонт'].fillna('Без ремонта')

In [ ]:
s = train["Адрес"].astype(str)
train["Город"] = (
    s.str.extract(r"(Москва|Санкт-Петербург|Екатеринбург)", expand=False)
     .astype("string")
)

In [ ]:
s = test["Адрес"].astype(str)
test["Город"] = (
    s.str.extract(r"(Москва|Санкт-Петербург|Екатеринбург)", expand=False)
     .astype("string")
)

In [ ]:
import re

def split(df, column_name):
    df = df.copy()

    def extract_count(text, type):
        if pd.isna(text):
            return 0
        match = re.search(rf'{type} \((\d+)\)', text)
        return int(match.group(1)) if match else 0

    df['Пассажирский_лифт'] = df[column_name].apply(lambda x: extract_count(x, 'Пасс'))
    df['Грузовой_лифт'] = df[column_name].apply(lambda x: extract_count(x, 'Груз'))

    return df

In [ ]:
train = split(train, 'Лифт')
test = split(test, 'Лифт')

In [ ]:
def extract_year_from_text(text):
    if pd.isna(text):
        return None

    text = str(text)
    match = re.search(r'(20\d{2}|19\d{2})', text)
    if match:
        return int(match.group(1))
    return None

train['Год_постройки'] = train['Название ЖК'].apply(extract_year_from_text)
test['Год_постройки'] = test['Название ЖК'].apply(extract_year_from_text)

year_mode = train['Год_постройки'].mode()[0]
train['Год_постройки'] = train['Год_постройки'].fillna(year_mode)
test['Год_постройки'] = test['Год_постройки'].fillna(year_mode)

from datetime import datetime
current_year = datetime.now().year
train['Возраст_дома'] = current_year - train['Год_постройки']
test['Возраст_дома'] = current_year - test['Год_постройки']

In [ ]:
train['Тип'].value_counts()

Тип
Продажа квартиры                  2261
Продажа квартиры в новостройке     260
Продажа доли в квартире             11
Name: count, dtype: int64

In [ ]:
df1=train[['Год_постройки','Возраст_дома','Балконы', "Лоджии", 'Санузел совмещенный', "Санузел раздельный", "Мусоропровод", 'Пассажирский_лифт', 'Грузовой_лифт','Парковка','Высота потолков, м','Количество комнат','Тип','Метро_станция','Метро_мин_пешком',"Площадь_общая","Площадь_жилая","Площадь_кухня","Этаж","Этажность","Материал",'Ремонт','Город']]
df2=test[['Год_постройки','Возраст_дома','Балконы', "Лоджии", 'Санузел совмещенный', "Санузел раздельный", "Мусоропровод", 'Пассажирский_лифт', 'Грузовой_лифт','Парковка','Высота потолков, м','Количество комнат','Тип','Метро_станция','Метро_мин_пешком',"Площадь_общая","Площадь_жилая","Площадь_кухня","Этаж","Этажность","Материал",'Ремонт','Город']]

In [ ]:
y_train=train['Стоимость']

In [ ]:
def trash(df, column_name):
    df = df.copy()
    df[column_name] = (
        df[column_name]
        .fillna('нет')
        .str.strip()
        .str.lower()
        .eq('да')
        .astype(int)
    )
    return df
df1 = trash(df1, 'Мусоропровод')
df2 = trash(df2, 'Мусоропровод')

In [ ]:
df1['Парковка']=df1['Парковка'].fillna('нет')
df2['Парковка']=df2['Парковка'].fillna('нет')

In [ ]:
df1['Высота потолков, м']=df1['Высота потолков, м'].fillna(2.9)
df2['Высота потолков, м']=df2['Высота потолков, м'].fillna(2.9)

In [ ]:
df1[df1['Город']=='Москва']['Метро_станция'].mode()

0    Парк Победы
Name: Метро_станция, dtype: object

In [ ]:
df1[df1['Город']=='Санкт-Петербург']['Метро_станция'].mode()

0    Комендантский проспект
Name: Метро_станция, dtype: object

In [ ]:
df1[df1['Город']=='Екатеринбург']['Метро_станция'].mode()

0    Ботаническая
Name: Метро_станция, dtype: object

In [ ]:
station = {
    'Москва': 'Парк Победы',
    'Санкт-Петербург': 'Комендантский проспект',
    'Екатеринбург': 'Ботаническая'
}

df1['Метро_станция'] = df1['Метро_станция'].fillna(
    df1['Город'].map(station)
)

df2['Метро_станция'] = df2['Метро_станция'].fillna(
    df2['Город'].map(station)
)

In [ ]:
df1['Метро_мин_пешком'].mean()

np.float64(15.070775347912525)

In [ ]:
df1['Метро_мин_пешком'] = df1['Метро_мин_пешком'].fillna(15)
df2['Метро_мин_пешком'] = df2['Метро_мин_пешком'].fillna(15)

In [ ]:
df1['Материал'].mode()

0    Монолитный
Name: Материал, dtype: string

In [ ]:
df1['Материал']=df1['Материал'].fillna('Монолитный')
df2['Материал']=df2['Материал'].fillna('Монолитный')

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2532 entries, 0 to 2531
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Год_постройки        2532 non-null   float64
 1   Возраст_дома         2532 non-null   float64
 2   Балконы              2532 non-null   int64
 3   Лоджии               2532 non-null   int64
 4   Санузел совмещенный  2532 non-null   int64
 5   Санузел раздельный   2532 non-null   int64
 6   Мусоропровод         2532 non-null   int64
 7   Пассажирский_лифт    2532 non-null   int64
 8   Грузовой_лифт        2532 non-null   int64
 9   Парковка             2532 non-null   object
 10  Высота потолков, м   2532 non-null   float64
 11  Количество комнат    2532 non-null   int64
 12  Тип                  2532 non-null   object
 13  Метро_станция        2532 non-null   object
 14  Метро_мин_пешком     2532 non-null   float64
 15  Площадь_общая        2532 non-null   float64
 16  Площадь_жилая        2532 non-null   float64
 17  Площадь_кухня        2532 non-null   float64
 18  Этаж                 2532 non-null   int64
 19  Этажность            2532 non-null   int64
 20  Материал             2532 non-null   string
 21  Ремонт               2532 non-null   object
 22  Город                2532 non-null   string
dtypes: float64(7), int64(10), object(4), string(2)
memory usage: 455.1+ KB

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 633 entries, 0 to 632
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Год_постройки        633 non-null    float64
 1   Возраст_дома         633 non-null    float64
 2   Балконы              633 non-null    int64
 3   Лоджии               633 non-null    int64
 4   Санузел совмещенный  633 non-null    int64
 5   Санузел раздельный   633 non-null    int64
 6   Мусоропровод         633 non-null    int64
 7   Пассажирский_лифт    633 non-null    int64
 8   Грузовой_лифт        633 non-null    int64
 9   Парковка             633 non-null    object
 10  Высота потолков, м   633 non-null    float64
 11  Количество комнат    633 non-null    int64
 12  Тип                  633 non-null    object
 13  Метро_станция        633 non-null    object
 14  Метро_мин_пешком     633 non-null    float64
 15  Площадь_общая        633 non-null    float64
 16  Площадь_жилая        633 non-null    float64
 17  Площадь_кухня        633 non-null    float64
 18  Этаж                 633 non-null    int64
 19  Этажность            633 non-null    int64
 20  Материал             633 non-null    string
 21  Ремонт               633 non-null    object
 22  Город                633 non-null    string
dtypes: float64(7), int64(10), object(4), string(2)
memory usage: 113.9+ KB

KNN (K-Nearest Neighbours)

In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsRegressor
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

X_train = df1.copy()
X_test  = df2.copy()

num_cols = [
     "Количество комнат", "Метро_мин_пешком",
     "Площадь_общая", "Площадь_жилая", "Площадь_кухня",
     "Этаж", "Этажность", 'Высота потолков, м', 'Балконы', "Лоджии",
     'Санузел совмещенный', "Санузел раздельный", "Мусоропровод",
     'Пассажирский_лифт', 'Грузовой_лифт', 'Год_постройки','Возраст_дома'
     ]
cat_cols = ["Тип", "Метро_станция", "Материал", "Ремонт", "Город", 'Парковка']

preprocess = ColumnTransformer(
     transformers=[
         ("num", StandardScaler(), num_cols),
         ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols),
         ],
     remainder="drop"
 )

pipe = Pipeline(steps=[
     ("prep", preprocess),
     ("knn", KNeighborsRegressor())
 ])

param_grid = {
     "knn__n_neighbors": list(range(3, 21)),
     "knn__weights": ["distance"],
     "knn__p": [1, 2], # 1=Manhattan, 2=Euclidean
 }

gs = GridSearchCV(
     pipe,
     param_grid=param_grid,
     cv=5,
     scoring="neg_mean_absolute_error",
     n_jobs=-1,
     verbose=1
)
gs.fit(X_train, y_train)

print("Best params:", gs.best_params_)
print("Best CV MAE:", -gs.best_score_)

y_pred_test = gs.predict(X_test)

Fitting 5 folds for each of 36 candidates, totalling 180 fits
Best params: {'knn__n_neighbors': 7, 'knn__p': 1, 'knn__weights': 'distance'}
Best CV MAE: 8019143.295553473

In [ ]:
gs.cv_results_

{'mean_fit_time': array([0.01861944, 0.01921811, 0.01899619, 0.0193295 , 0.01970463,
        0.01853733, 0.0185739 , 0.01867352, 0.01776266, 0.01858859,
        0.01848178, 0.01935205, 0.01863918, 0.01799355, 0.01801596,
        0.0187253 , 0.02743964, 0.03680902, 0.0329143 , 0.03536396,
        0.01898293, 0.01915951, 0.01721401, 0.01785126, 0.01922636,
        0.01837335, 0.01768346, 0.01828666, 0.01862731, 0.01780624,
        0.01844215, 0.01867275, 0.0182621 , 0.02297544, 0.01769085,
        0.01813602]),
 'std_fit_time': array([0.00257952, 0.00224388, 0.00112388, 0.00073923, 0.00174208,
        0.00156484, 0.00103102, 0.00112971, 0.00064035, 0.00012306,
        0.00106162, 0.00066136, 0.00120363, 0.00010455, 0.0002657 ,
        0.00052101, 0.00794518, 0.00614059, 0.00383455, 0.00770233,
        0.00308071, 0.00180195, 0.00065471, 0.00165134, 0.00044518,
        0.00073889, 0.00088433, 0.00150835, 0.00106896, 0.00081849,
        0.00034235, 0.00067537, 0.00038855, 0.00847803, 0.00142466,
        0.00090384]),
 'mean_score_time': array([0.11853795, 0.10235734, 0.11185927, 0.09546766, 0.11661754,
        0.09797192, 0.11076965, 0.10274744, 0.11112647, 0.09762254,
        0.11318707, 0.10049033, 0.11202626, 0.0989996 , 0.11861591,
        0.09805527, 0.159799  , 0.18011928, 0.17422295, 0.14024053,
        0.11839366, 0.10408688, 0.11057005, 0.09759617, 0.1176362 ,
        0.09860196, 0.11307521, 0.10378981, 0.11355829, 0.09754405,
        0.11744604, 0.09885406, 0.11362   , 0.09821644, 0.11157393,
        0.09975009]),
 'std_score_time': array([0.00735647, 0.0093273 , 0.00322285, 0.00177851, 0.00833135,
        0.00185349, 0.00214462, 0.00789625, 0.00106815, 0.00228712,
        0.00285434, 0.00481117, 0.00437938, 0.00258237, 0.00678109,
        0.00183749, 0.03513606, 0.04094397, 0.02934399, 0.01993489,
        0.01454027, 0.0079752 , 0.00247268, 0.00386376, 0.00721828,
        0.00178805, 0.0030555 , 0.00880998, 0.00291128, 0.00249923,
        0.00874236, 0.001803  , 0.00323069, 0.00230615, 0.00210732,
        0.00388549]),
 'param_knn__n_neighbors': masked_array(data=[3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11,
                    11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16, 17, 17, 18,
                    18, 19, 19, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=999999),
 'param_knn__p': masked_array(data=[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2,
                    1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=999999),
 'param_knn__weights': masked_array(data=['distance', 'distance', 'distance', 'distance',
                    'distance', 'distance', 'distance', 'distance',
                    'distance', 'distance', 'distance', 'distance',
                    'distance', 'distance', 'distance', 'distance',
                    'distance', 'distance', 'distance', 'distance',
                    'distance', 'distance', 'distance', 'distance',
                    'distance', 'distance', 'distance', 'distance',
                    'distance', 'distance', 'distance', 'distance',
                    'distance', 'distance', 'distance', 'distance'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'knn__n_neighbors': 3, 'knn__p': 1, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 3, 'knn__p': 2, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 4, 'knn__p': 1, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 4, 'knn__p': 2, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 5, 'knn__p': 1, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 5, 'knn__p': 2, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 6, 'knn__p': 1, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 6, 'knn__p': 2, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 7, 'knn__p': 1, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 7, 'knn__p': 2, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 8, 'knn__p': 1, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 8, 'knn__p': 2, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 9, 'knn__p': 1, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 9, 'knn__p': 2, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 10, 'knn__p': 1, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 10, 'knn__p': 2, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 11, 'knn__p': 1, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 11, 'knn__p': 2, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 12, 'knn__p': 1, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 12, 'knn__p': 2, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 13, 'knn__p': 1, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 13, 'knn__p': 2, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 14, 'knn__p': 1, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 14, 'knn__p': 2, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 15, 'knn__p': 1, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 15, 'knn__p': 2, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 16, 'knn__p': 1, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 16, 'knn__p': 2, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 17, 'knn__p': 1, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 17, 'knn__p': 2, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 18, 'knn__p': 1, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 18, 'knn__p': 2, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 19, 'knn__p': 1, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 19, 'knn__p': 2, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 20, 'knn__p': 1, 'knn__weights': 'distance'},
  {'knn__n_neighbors': 20, 'knn__p': 2, 'knn__weights': 'distance'}],
 'split0_test_score': array([ -9368882.73721933, -10197520.80256883,  -8689326.97389769,
         -9695969.76328501,  -8854196.12698654,  -9177595.69802762,
         -8588958.77762195,  -9366242.83275284,  -8636237.34858101,
         -9582466.08923931,  -8479163.9294671 ,  -9550304.26603491,
         -8298851.09819533,  -9613108.11185099,  -8106244.67605721,
         -9746767.10693767,  -8085334.22182032,  -9564061.81444835,
         -8095843.09521605,  -9436439.9050097 ,  -8098427.74908426,
         -9259400.53558877,  -8175110.22200839,  -9144592.54050584,
         -8107525.52473477,  -9047560.7354791 ,  -8029923.8758621 ,
         -9023664.49233054,  -7984799.68916538,  -8974763.66241786,
         -7969849.40521529,  -8900224.08843185,  -7943480.69713897,
         -8874023.46245064,  -7971484.59440071,  -8838380.21813551]),
 'split1_test_score': array([-8126330.08871155, -7832265.19121098, -7544699.3140846 ,
        -7680936.89894993, -7363338.11411811, -8169912.55201247,
        -7334473.10005135, -8205359.97587702, -7261056.27476969,
        -8382730.16041751, -7178158.37497109, -8769158.14937384,
        -7279836.82585765, -8652806.03506593, -7460661.32229178,
        -8494497.05736292, -7472503.78989799, -8453481.07752887,
        -7626081.64002635, -8473608.56045565, -7677232.76377941,
        -8523633.9510158 , -7767085.08532448, -8576753.8987387 ,
        -7768329.49787477, -8709908.35062115, -7747035.7095219 ,
        -8818457.32044648, -7750166.3735673 , -8807330.73627762,
        -7756942.13712336, -8938893.9805075 , -7757702.9515078 ,
        -9011879.72729703, -7784662.96731587, -9025234.00131416]),
 'split2_test_score': array([-8457063.32236451, -9850549.59028618, -8042023.51647997,
        -9368240.21370494, -8126943.77497798, -9267269.80216955,
        -7961327.40304381, -9231758.00495742, -7928246.82225683,
        -9297247.507843  , -8115894.45981509, -9333798.4814473 ,
        -8227740.36816912, -9386931.99219187, -8231108.75518538,
        -9243042.43670122, -8223591.91525612, -9315313.8602683 ,
        -8124969.20979046, -9395631.67459   , -8142915.14462415,
        -9345974.26320864, -8156164.18321604, -9405301.64853018,
        -8120720.63625461, -9393891.80627251, -8151038.45108347,
        -9358144.27282382, -8212769.83894013, -9406541.56807148,
        -8302488.73542826, -9381160.66771593, -8339847.93268781,
        -9269619.09340751, -8345578.17758611, -9246537.05178665]),
 'split3_test_score': array([-8799848.59083857, -9458554.61656412, -8412223.75308737,
        -9443008.59451116, -8301704.48920617, -9413115.22805515,
        -8210453.36438988, -9271802.56648148, -8095539.72268919,
        -9341014.8865722 , -8099123.37671586, -9167012.11419517,
        -8205996.19245321, -9160737.04322363, -8120444.55008319,
        -9275691.0759412 , -8100850.36786358, -9237602.95680608,
        -8036846.68702881, -9264475.73930541, -7886234.17440553,
        -9254762.73413276, -7896212.34163319, -9129624.40496901,
        -7875451.90000015, -9200188.22126351, -7955168.02962597,
        -9073706.24084253, -7897037.60561559, -9184578.43664461,
        -7948400.32117916, -9162197.76336157, -7985452.71058307,
        -9241351.69035389, -7974134.30879473, -9250679.93306385]),
 'split4_test_score': array([ -8291213.22795183,  -9952305.90558261,  -8091934.26957633,
         -9558791.81198586,  -8156320.26940322,  -9524270.99931457,
         -8162931.57397884,  -9855642.05036089,  -8174636.30947064,
        -10016424.41760966,  -8385338.32605097, -10163144.57591892,
         -8358536.85580954, -10372342.84292215,  -8522200.5837179 ,
        -10457835.10375732,  -8549646.43560909, -10569017.48144253,
         -8759343.85547351, -10529986.61286144,  -8875779.13737544,
        -10466205.7416576 ,  -8908491.16760784, -10412427.05374094,
         -9021912.58826576, -10410017.35160495,  -8984404.43382325,
        -10377727.65908095,  -8962639.80572638, -10450384.38987496,
         -8906343.31589526, -10463021.47626353,  -8813553.2495643 ,
        -10567323.25625894,  -8862891.65231426, -10459598.46747533]),
 'mean_test_score': array([-8608667.59341716, -9458239.22124254, -8156041.56542519,
        -9149389.45648738, -8160500.5549384 , -9110432.85591587,
        -8051628.84381717, -9186161.08608593, -8019143.29555347,
        -9323976.61233634, -8051535.69340402, -9396683.51739403,
        -8074192.26809697, -9437185.20505092, -8088131.97746709,
        -9443566.55614007, -8086385.34608942, -9427895.43809883,
        -8128616.89750704, -9420028.49844444, -8136117.79385376,
        -9369995.44512071, -8180612.59995799, -9333739.90929693,
        -8178788.02942601, -9352313.29304824, -8173514.09998334,
        -9330339.99710486, -8161482.66260296, -9364719.7586573 ,
        -8176804.78296827, -9369099.59525608, -8168007.50829639,
        -9392839.4459536 , -8187750.34008234, -9364085.9343551 ]),
 'std_test_score': array([440655.83764231, 847152.66824033, 384934.24095696, 742539.03417309,
        477024.86036997, 485090.86663445, 412020.31378593, 538891.18697026,
        445820.06721921, 535397.12434102, 461190.78147996, 460771.84318279,
        400817.48879741, 565626.79050635, 347548.41654211, 646497.68344943,
        349427.3562372 , 681038.91020138, 363281.53814647, 656167.49613772,
        405359.82550011, 623552.98440685, 395556.24701993, 603184.00584222,
        442673.28855073, 574311.22522801, 426198.37276619, 551312.72739759,
        427741.11173189, 578898.25191994, 404797.89892073, 573505.01848161,
        373723.64333617, 605284.12304051, 383564.21351201, 568860.87995871]),
 'rank_test_score': array([18, 36,  9, 20, 10, 19,  3, 21,  1, 22,  2, 31,  4, 34,  6, 35,  5,
        33,  7, 32,  8, 29, 16, 24, 15, 25, 13, 23, 11, 27, 14, 28, 12, 30,
        17, 26], dtype=int32)}

In [ ]:
subm=pd.DataFrame({'id':[i for i in range(test.shape[0])],'Стоимость':y_pred_test})

In [ ]:
test.shape[0]

633

In [ ]:
subm

      id     Стоимость
0      0  7.922265e+06
1      1  6.166674e+06
2      2  7.629627e+06
3      3  6.607098e+06
4      4  7.087135e+07
..   ...           ...
628  628  1.201427e+07
629  629  1.072020e+07
630  630  8.663884e+06
631  631  8.974451e+06
632  632  1.389523e+07

[633 rows x 2 columns]

In [ ]:
subm.to_csv('my_solution.csv',index=False)